name: Python Package using Conda

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Conda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv  # Name your Conda environment
          python-version: 3.8  # Specify your Python version here
          environment-file: environment.yml  # Reference your Conda environment file if you have one
          auto-update-conda: true
          auto-activate-base: false

      # Step 3: Install dependencies from environment.yml or requirements.txt
      - name: Install dependencies
        run: |
          conda env update -f environment.yml || conda install --file requirements.txt
          conda activate myenv

      # Step 4: Run tests (or any other commands/scripts)
      - name: Run tests
        run: |
          conda activate myenv
          pytest  # Run your tests; adjust as needed

      # Optional: Deactivate Conda environment
      - name: Deactivate Conda environment
        run: conda deactivate